name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always
  ANDROID_API_LEVEL: 29
  NDK_VERSION: r27d

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    needs: test
    
    strategy:
      matrix:
        build-type: [debug, release]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-linux-android
    
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: ${{ env.NDK_VERSION }}
    
    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
    
    - name: Install cargo-ndk
      run: cargo install cargo-ndk
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-android-${{ matrix.build-type }}-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Set up build environment
      run: |
        echo "CC_aarch64_linux_android=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android${{ env.ANDROID_API_LEVEL }}-clang" >> $GITHUB_ENV
        echo "AR_aarch64_linux_android=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" >> $GITHUB_ENV
        echo "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android${{ env.ANDROID_API_LEVEL }}-clang" >> $GITHUB_ENV
        echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
        echo "OPENSSL_STATIC=1" >> $GITHUB_ENV
        echo "OPENSSL_NO_VENDOR=1" >> $GITHUB_ENV
    
    - name: Test network features on host
      run: cargo check --features "network"
    
    - name: Clean build artifacts
      run: |
        # Clean any existing build artifacts to ensure fresh build
        rm -rf target/aarch64-linux-android/
        cargo clean --target aarch64-linux-android

    - name: Build Rust library for Android
      run: |
        if [ "${{ matrix.build-type }}" = "release" ]; then
          cargo ndk -t arm64-v8a build --release --no-default-features --features "filter-engine,performance-monitoring"
        else
          cargo ndk -t arm64-v8a build --no-default-features --features "filter-engine,performance-monitoring"
        fi
    
    - name: Build C++ ZygiskNext module
      run: |
        BUILD_TYPE="Release"
        if [ "${{ matrix.build-type }}" = "debug" ]; then
          BUILD_TYPE="Debug"
        fi
        
        # Create clean build directory
        BUILD_DIR="target/aarch64-linux-android/cpp_build"
        rm -rf "$BUILD_DIR"
        mkdir -p "$BUILD_DIR"
        cd "$BUILD_DIR"
        
        # Configure with CMake using Unix Makefiles (more reliable in CI)
        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
              -DANDROID_ABI=arm64-v8a \
              -DANDROID_PLATFORM=android-${{ env.ANDROID_API_LEVEL }} \
              -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
              ../../../src/cpp
        
        # Build with make
        make -j$(nproc)
        
        # Copy built module to expected location
        cp libaubo_module.so ../aubo_module.so
        
        cd ../../..
    
    - name: Validate built modules
      run: |
        echo "=== Validating Rust library ==="
        RUST_LIB="target/aarch64-linux-android/${{ matrix.build-type }}/libaubo_rs.so"
        if [ -f "$RUST_LIB" ]; then
          echo "✓ Rust library found: $RUST_LIB"
          echo "Size: $(stat -c%s "$RUST_LIB") bytes"
          
          # Check for required C exports
          if $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-nm "$RUST_LIB" | grep -q "aubo_initialize"; then
            echo "✓ aubo_initialize symbol found"
          else
            echo "✗ aubo_initialize symbol missing"
            exit 1
          fi
        else
          echo "✗ Rust library not found: $RUST_LIB"
          exit 1
        fi
        
        echo "=== Validating C++ ZygiskNext module ==="
        CPP_MODULE="target/aarch64-linux-android/aubo_module.so"
        if [ -f "$CPP_MODULE" ]; then
          echo "✓ C++ module found: $CPP_MODULE"
          echo "Size: $(stat -c%s "$CPP_MODULE") bytes"
          
          # Check for required ZygiskNext exports
          if $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-nm "$CPP_MODULE" | grep -q "zn_module"; then
            echo "✓ zn_module symbol found"
          else
            echo "✗ zn_module symbol missing"
            exit 1
          fi
          
          if $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-nm "$CPP_MODULE" | grep -q "zn_companion_module"; then
            echo "✓ zn_companion_module symbol found"
          else
            echo "✗ zn_companion_module symbol missing"
            exit 1
          fi
        else
          echo "✗ C++ module not found: $CPP_MODULE"
          exit 1
        fi
        
        echo "=== All modules validated successfully ==="
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aubo-rs-modules-${{ matrix.build-type }}
        path: |
          target/aarch64-linux-android/${{ matrix.build-type }}/libaubo_rs.so
          target/aarch64-linux-android/aubo_module.so

  package:
    name: Package Magisk Module
    runs-on: ubuntu-latest
    needs: build-android
    if: github.event_name == 'release' || github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: aubo-rs-modules-release
        path: artifacts/
    
    - name: Generate version info
      id: version
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          VERSION="${{ github.event.release.tag_name }}"
        else
          VERSION="dev-$(git rev-parse --short HEAD)"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "code=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
        echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    
    - name: Prepare module structure
      run: |
        mkdir -p build/module/lib/arm64
        
        # Copy both libraries to the module structure
        cp artifacts/libaubo_rs.so build/module/lib/arm64/
        cp artifacts/aubo_module.so build/module/lib/arm64/
        
        # Copy template files
        cp -r template/* build/module/
        cp aubo-rs.toml build/module/
        cp README.md build/module/
        
        # Verify both libraries are present
        ls -la build/module/lib/arm64/
        echo "Rust library size: $(stat -c%s build/module/lib/arm64/libaubo_rs.so) bytes"
        echo "C++ module size: $(stat -c%s build/module/lib/arm64/aubo_module.so) bytes"
    
    - name: Process templates
      run: |
        sed -i "s/\${moduleId}/aubo_rs/g" build/module/module.prop
        sed -i "s/\${moduleName}/aubo-rs/g" build/module/module.prop
        sed -i "s/\${versionName}/${{ steps.version.outputs.version }} (${{ steps.version.outputs.code }}-${{ steps.version.outputs.hash }})/g" build/module/module.prop
        sed -i "s/\${versionCode}/${{ steps.version.outputs.code }}/g" build/module/module.prop
        
        sed -i "s/@DEBUG@/false/g" build/module/customize.sh
        sed -i "s/@SONAME@/aubo_rs/g" build/module/customize.sh
        sed -i "s/@VERSION@/${{ steps.version.outputs.version }} (${{ steps.version.outputs.code }}-${{ steps.version.outputs.hash }})/g" build/module/customize.sh
        sed -i "s/@SUPPORTED_ABIS@/arm64/g" build/module/customize.sh
        sed -i "s/@MIN_SDK@/${{ env.ANDROID_API_LEVEL }}/g" build/module/customize.sh
    
    - name: Create module ZIP
      run: |
        cd build/module
        zip -r "../../aubo-rs-${{ steps.version.outputs.version }}.zip" . -x "*.git*"
        cd ../..
        
        # Generate checksums
        sha256sum "aubo-rs-${{ steps.version.outputs.version }}.zip" > "aubo-rs-${{ steps.version.outputs.version }}.zip.sha256"
        md5sum "aubo-rs-${{ steps.version.outputs.version }}.zip" > "aubo-rs-${{ steps.version.outputs.version }}.zip.md5"
    
    - name: Validate final module package
      run: |
        echo "=== Validating final Magisk module package ==="
        MODULE_ZIP="aubo-rs-${{ steps.version.outputs.version }}.zip"
        
        # Check ZIP contents
        echo "Module ZIP contents:"
        unzip -l "$MODULE_ZIP"
        
        # Extract and verify libraries
        unzip -j "$MODULE_ZIP" "lib/arm64/*" -d temp_extract/
        
        if [ -f "temp_extract/libaubo_rs.so" ]; then
          echo "✓ Rust library found in ZIP ($(stat -c%s temp_extract/libaubo_rs.so) bytes)"
        else
          echo "✗ Rust library missing from ZIP"
          exit 1
        fi
        
        if [ -f "temp_extract/aubo_module.so" ]; then
          echo "✓ C++ ZygiskNext module found in ZIP ($(stat -c%s temp_extract/aubo_module.so) bytes)"
        else
          echo "✗ C++ ZygiskNext module missing from ZIP"
          exit 1
        fi
        
        # Verify zn_modules.txt
        if unzip -p "$MODULE_ZIP" "zn_modules.txt" | grep -q "aubo_module"; then
          echo "✓ zn_modules.txt correctly configured"
        else
          echo "✗ zn_modules.txt configuration issue"
          exit 1
        fi
        
        rm -rf temp_extract/
        echo "=== Module package validation successful ==="
        
        # Show final module information
        echo "=== Final Module Information ==="
        echo "Module ZIP: $MODULE_ZIP"
        echo "ZIP size: $(stat -c%s "$MODULE_ZIP") bytes"
        echo "SHA256: $(cat "aubo-rs-${{ steps.version.outputs.version }}.zip.sha256")"
        echo "Contents summary:"
        echo "  ✓ Rust library (libaubo_rs.so) - Core filtering engine"
        echo "  ✓ C++ module (aubo_module.so) - ZygiskNext integration"
        echo "  ✓ Configuration files and scripts"
        echo "  ✓ Installation and diagnostic tools"
        echo "Ready for deployment!"
    
    - name: Upload module artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aubo-rs-module
        path: |
          aubo-rs-*.zip
          aubo-rs-*.zip.sha256
          aubo-rs-*.zip.md5
    
    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          aubo-rs-*.zip
          aubo-rs-*.zip.sha256
          aubo-rs-*.zip.md5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install cargo-audit
      run: cargo install cargo-audit
    
    - name: Run security audit
      run: cargo audit

  documentation:
    name: Generate Documentation
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Generate docs
      run: cargo doc --no-deps
    
    - name: Upload documentation
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: target/doc/
